/**
 * PROPERTY INPUTS
 */
export const UPDATE_MIN_PRICE = 'UPDATE_MIN_PRICE';
export const UPDATE_MAX_PRICE = 'UPDATE_MAX_PRICE';
export const UPDATE_MIN_BEDS = 'UPDATE_MIN_BEDS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_RADIUS = 'UPDATE_RADIUS';
export const UPDATE_TYPE = 'UPDATE_TYPE';
export const UPDATE_ORDER_BY = 'UPDATE_ORDER_BY';

/**
 * PURCHASE INPUTS
 */
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_STAMP_DUTY = 'UPDATE_STAMP_DUTY';
export const UPDATE_BUY_TO_LET = 'UPDATE_BUY_TO_LET';
export const UPDATE_SURVEY_FEES = 'UPDATE_SURVEY_FEES';
export const UPDATE_PURCHASE_LEGAL_FEES = 'UPDATE_PURCHASE_LEGAL_FEES';
export const UPDATE_PURCHASE_AGENT_FEES = 'UPDATE_PURCHASE_AGENT_FEES';
export const UPDATE_HOLD_PERIOD = 'UPDATE_HOLD_PERIOD';
export const UPDATE_GROWTH = 'UPDATE_GROWTH';
export const UPDATE_RENTAL_INCOME = 'UPDATE_RENTAL_INCOME';
export const UPDATE_SALE_LEGAL_FEES = 'UPDATE_SALE_LEGAL_FEES';
export const UPDATE_SALE_AGENT_FEES = 'UPDATE_SALE_AGENT_FEES';

/**
 * MORTGAGE INPUTS
 */
export const UPDATE_DEPOSIT = 'UPDATE_DEPOSIT';
export const UPDATE_INTEREST_RATE = 'UPDATE_INTEREST_RATE';
export const UPDATE_BROKER_FEE = 'UPDATE_BROKER_FEE';
export const UPDATE_LOAN_TYPE = 'UPDATE_LOAN_TYPE';
export const UPDATE_TERM = 'UPDATE_TERM';
export const UPDATE_GOVERNMENT_LOAN = 'UPDATE_GOVERNMENT_LOAN';
export const UPDATE_MORTGAGE_SIZE = 'UPDATE_MORTGAGE_SIZE';
export const UPDATE_HOUSEHOLD_INCOME = 'UPDATE_HOUSEHOLD_INCOME';

/**
 * LISTINGS
 */
export const UPDATE_LISTING = 'UPDATE_LISTING';
export const UPDATE_ADMIN_DISTRICT = 'UPDATE_ADMIN_DISTRICT';
export const UPDATE_REGION = 'UPDATE_REGION';
export const UPDATE_FIVE_YEAR_GROWTH = 'UPDATE_FIVE_YEAR_GROWTH';

/**
 * NAVIGATION
 */
export const UPDATE_NAV_ACTIVE = 'UPDATE_NAV_ACTIVE';
export const UPDATE_APP_LOADING = 'UPDATE_APP_LOADING';
